### ISSUE TITLE
Caching Problem (related to JS-SDK)

### ISSUE THREAD

**Issue by Patrick3131** [medusajs/nextjs-starter-medusa#402] opened 2024-11-13 12:31 UTC
I am experiencing caching problems in various places, basically anywhere the JS-SDk is used. 

But to reproduce here is a specific example.
1. Use the frontend and perform requests related to product categories.
2. Add a new category in the backend.
3. Refresh the frontend
4. The new category does not appear in the front end.

The SDK is performing a request:

> Performing request to:
>  URL: http://localhost:9000/store/product-categories?limit=6&offset=0
>  Headers: {
>   "accept": "application/json",
>   "content-type": "application/json",
>   "next": "[object Object]",
>   "x-publishable-api-key": "pk_a2a7ef77ac474db492f87f3c9103ebc6a8ddf917ba0bb004d6219930dd71bd9f",
>   "authorization": "<REDACTED>"
> }
However, it is only returning the previously cached request without the newly added category.

Adding no caching to the Medusa SDK init fixes the issue:

```
export const sdk = new Medusa({
  baseUrl: MEDUSA_BACKEND_URL,
  debug: process.env.NODE_ENV === "development",
  publishableKey: process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY,
  globalHeaders: {
    "Cache-Control": "no-store",  // Prevents caching
    Pragma: "no-cache",            // For HTTP/1.0 compatibility
  },
})
```

But also then removes the caching completely 😛

**Comment by sradevski** [comment] 2024-11-14 08:52
Thanks for opening a ticket with reproduction steps.

This is more of a NextJS caching behavior, not an issue with the SDK itself. That being said, we need to make the entire caching story better, probably by first upgrading to NextJs 15, as they've done some changes to how caching works out of the box.

We'll keep this ticket updated once we get this looked into. Also feel free to open a PR if you want to help with a fix

**Comment by Patrick3131** [comment] 2024-11-14 12:55
Well we are using the SDK within Nextjs so we have to find a solution that makes it feasible to use it within Nextjs.

Medusa has this [article](https://medusajs.com/blog/client-server-transition-learnings-nextjs-14-server-components/) on their website, talking about benefits and also pointing out challenges (reading the article makes you think these challenges are solved):

> If a product sells out, it should be immediately clear to all customers. And with multi-currency and personalized prices, the customer should see the price they will be charged in real time. Ecommerce websites, therefore, have to interact with a server that can deliver this information. 

> At first, re-fetching the same data multiple times in a component tree seemed counterintuitive as you’d normally fetch data in one place, and pass it down via either Context or props. You must also remember to revalidate the relevant parts of the cache every time you mutate data on the server. These patterns take some getting used to.

But basically this starter doesn't live up to its promises because currently we have to disable the caching (simultaneously also removing benefits of Nextjs SSR) to use it. 
This https://github.com/medusajs/nextjs-starter-medusa/issues/54 probably also stems from a caching problem.

What would be a caching strategy moving forward? 

I understand the caching is caused by Nextjs extension of the fetch API and that is not the case when the Medusa SDK is used in another context. However, I think this should still be something that the SDK handles automatically, because this logic will be necessary in any implementation with Nextjs. Do you think we should move this issue to a different repository? If Nextjs is a common storefront technology, maybe a more specific SDK targeting Nextjs specific challenges could make more sense?

One idea would be to subscribe/listen to changes from the medusa backend and purge the cache when necessary. Maybe a temporary solution could be to purge the complete cache with any change that is coming from the backend and in the future a more targeted approach?

If I understand it correctly, I also found other inefficient ways how the cache is used:

```
export async function updateCart(data: HttpTypes.StoreUpdateCart) {
  const cartId = getCartId()
  if (!cartId) {
    throw new Error("No existing cart found, please create one before updating")
  }

  return sdk.store.cart
    .update(cartId, data, {}, getAuthHeaders())
    .then(({ cart }) => {
      revalidateTag("cart")
      return cart
    })
    .catch(medusaError)
}

```
or 

```
export const updateCustomer = cache(async function (
  body: HttpTypes.StoreUpdateCustomer
) {
  const updateRes = await sdk.store.customer
    .update(body, {}, getAuthHeaders())
    .then(({ customer }) => customer)
    .catch(medusaError)

  revalidateTag("customer")
  return updateRes
})
```

This purges the cache for any user, would it not make more sense to have a more user specific cache and only purge the cache necessary?

Temporarily, what would make sense to target? Disabling the caching completely till there is a more sophisticated cache handling solution?

**Comment by RoxDevvv** [comment] 2024-11-29 19:40
is that fixed ! am running into issue where products won't appears in frontend unless i accessed via a direct link.

**Comment by VariableVic** [comment] 2024-12-02 16:29
Hey guys, 

I recently addressed a bunch of the issues mentioned in this thread:
- Implemented dynamic cache tags. These will ensure that we're only revalidating cache for the current user.
- Refactored the js-sdk GET requests to use `sdk.client.fetch`. This is a temporary fix until the js-sdk properly pases the Next cache tags (we're working on this).
- Updated to Next.js 15.

Just tried to reproduce the original issue (categories not updating), and my newly created categories show up on the frontend immediately. Can you pull the latest changes and see if this fixes your issue?

**Comment by prometixX** [comment] 2024-12-06 17:01
> Hey guys,
> ...
> Just tried to reproduce the original issue (categories not updating), and my newly created categories show up on the frontend immediately. Can you pull the latest changes and see if this fixes your issue?

I cloned the repo with your latest changes (caching fixes which introduced next 15 and react 19 RC). 
Because next 15 doesnt cache on default, the issues here might be fixed but disabling the caching completely introduces another problem. 
Now even static generated pages (SSG) like `[countryCode]/products/[handle]` are slow because they fetch region and product on every page load, without caching. 
So this is defeating the purpose of static generated pages. 

To fix this isssue I think we should cache the get requests with `{ cache: "force-cache" }` and have some revalidation logic to clear the cache.

**Comment by VariableVic** [comment] 2024-12-11 15:24
Hey all,

I just merged a fix adding `{ cache: "force-cache" }` headers to all relevant GET requests. Caching now works as it should again. Closing this issue, but feel free to re-open if you're still experiencing issues.

**Closed by VariableVic** 2024-12-11 15:24 UTC
