### ISSUE TITLE
Error: A "use server" file can only export async functions.

### ISSUE THREAD

**Issue by mjp0** [medusajs/nextjs-starter-medusa#286] opened 2024-03-06 10:34 UTC
I just started a new project and when I try to load the storefront for the first time, it crashes with `Error: A "use server" file can only export async functions.`.

This happens right after running the setup with `npm run dev`, so no idea what's going on. NodeJS is v20.5.0 and tried with bun also.

Stack trace:
```
> medusa-next@1.0.3 dev
> next dev -p 8000

next.config.js {}
next.config.js {}
   ▲ Next.js 14.1.2
   - Local:        http://localhost:8000
   - Environments: .env.local

/bin/sh: yarn: command not found
 ✓ Ready in 2.4s
 ○ Compiling /src/middleware ...
 ✓ Compiled /src/middleware in 2.3s (3797 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ○ Compiling /[countryCode] ...
 ✓ Compiled /[countryCode] in 2.1s (4549 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ⨯ node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js (24:18) @ ensureServerEntryExports
 ⨯ Error: A "use server" file can only export async functions.
Read more: https://nextjs.org/docs/messages/invalid-use-server-value
    at ensureServerEntryExports (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js:24:19)
    at eval (webpack-internal:///(rsc)/./src/lib/data/index.ts:564:91)
    at (rsc)/./src/lib/data/index.ts (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:698:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/modules/layout/templates/footer/index.tsx:9:67)
    at (rsc)/./src/modules/layout/templates/footer/index.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:1115:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/[countryCode]/(main)/layout.tsx:8:90)
    at (rsc)/./src/app/[countryCode]/(main)/layout.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:577:1)
    at Function.__webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42) {
  type: 'Error',
  page: '/us'
}
null
 ⨯ node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js (24:18) @ ensureServerEntryExports
 ⨯ Error: A "use server" file can only export async functions.
Read more: https://nextjs.org/docs/messages/invalid-use-server-value
    at ensureServerEntryExports (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js:24:19)
    at eval (webpack-internal:///(rsc)/./src/lib/data/index.ts:564:91)
    at (rsc)/./src/lib/data/index.ts (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:698:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/modules/layout/templates/footer/index.tsx:9:67)
    at (rsc)/./src/modules/layout/templates/footer/index.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:1115:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/[countryCode]/(main)/layout.tsx:8:90)
    at (rsc)/./src/app/[countryCode]/(main)/layout.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:577:1)
    at Function.__webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42) {
  type: 'Error',
  page: '/us'
}
null
 ⨯ node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js (24:18) @ ensureServerEntryExports
 ⨯ Error: A "use server" file can only export async functions.
Read more: https://nextjs.org/docs/messages/invalid-use-server-value
    at ensureServerEntryExports (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js:24:19)
    at eval (webpack-internal:///(rsc)/./src/lib/data/index.ts:564:91)
    at (rsc)/./src/lib/data/index.ts (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:698:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/modules/layout/templates/footer/index.tsx:9:67)
    at (rsc)/./src/modules/layout/templates/footer/index.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:1115:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/[countryCode]/(main)/layout.tsx:8:90)
    at (rsc)/./src/app/[countryCode]/(main)/layout.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:577:1)
    at Function.__webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42) {
  type: 'Error',
  page: '/us'
}
null
 ✓ Compiled /_error in 303ms (4711 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ⨯ node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js (24:18) @ ensureServerEntryExports
 ⨯ Error: A "use server" file can only export async functions.
Read more: https://nextjs.org/docs/messages/invalid-use-server-value
    at ensureServerEntryExports (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js:24:19)
    at eval (webpack-internal:///(rsc)/./src/lib/data/index.ts:564:91)
    at (rsc)/./src/lib/data/index.ts (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:698:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/modules/layout/templates/footer/index.tsx:9:67)
    at (rsc)/./src/modules/layout/templates/footer/index.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:1115:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/[countryCode]/(main)/layout.tsx:8:90)
    at (rsc)/./src/app/[countryCode]/(main)/layout.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:577:1)
    at Function.__webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42) {
  type: 'Error',
  page: '/us'
}
null
 ⨯ node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js (24:18) @ ensureServerEntryExports
 ⨯ Error: A "use server" file can only export async functions.
Read more: https://nextjs.org/docs/messages/invalid-use-server-value
    at ensureServerEntryExports (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-flight-loader/action-validate.js:24:19)
    at eval (webpack-internal:///(rsc)/./src/lib/data/index.ts:564:91)
    at (rsc)/./src/lib/data/index.ts (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:698:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/modules/layout/templates/footer/index.tsx:9:67)
    at (rsc)/./src/modules/layout/templates/footer/index.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:1115:1)
    at __webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/[countryCode]/(main)/layout.tsx:8:90)
    at (rsc)/./src/app/[countryCode]/(main)/layout.tsx (/Users/marko/Dev/medusa-storefront/.next/server/app/[countryCode]/(main)/page.js:577:1)
    at Function.__webpack_require__ (/Users/marko/Dev/medusa-storefront/.next/server/webpack-runtime.js:33:42) {
  type: 'Error',
  page: '/us'
}
null
```

**Comment by snsa-kscc** [comment] 2024-03-06 11:51
Having exactly the same error after loading the storefront for the first time.

**Comment by VariableVic** [comment] 2024-03-06 12:46
Hey guys, I suspect this was caused by a redundant `"use server"` declaration in `src/lib/data/index.ts`. I've just pushed a fix, lmk if that solves the issue!

**Comment by mjp0** [comment] 2024-03-06 12:55
I also had to comment `use server` in `/src/lib/data/index.ts`.

**Comment by snsa-kscc** [comment] 2024-03-06 13:18
Great, that fixed the issue for me. Thanks for the fast fix.

**Closed** 2024-03-06 13:56 UTC
